SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID 
    AND (H.END_DATE > '2022-11-01' 
        AND H.START_DATE < '2022-12-01')
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE H.CAR_ID IS NULL 
    AND P.DURATION_TYPE = '30일 이상' 
    AND C.CAR_TYPE IN ('세단', 'SUV')
HAVING (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC