-- 코드를 입력하세요
SELECT ICECREAM.FLAVOR
FROM  FIRST_HALF AS FH
INNER JOIN ICECREAM_INFO AS ICECREAM
ON FH.FLAVOR=ICECREAM.FLAVOR
WHERE FH.TOTAL_ORDER>3000 AND ICECREAM.INGREDIENT_TYPE='fruit_based'
ORDER BY FH.TOTAL_ORDER DESC