-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (SUM(FD.AMOUNT)*FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FD
    ON FP.PRODUCT_ID=FD.PRODUCT_ID
WHERE DATE_FORMAT(FD.PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY FD.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID